[[default_users]]
role = "admin"
name = "admin"
password = "1234"
email = "admin@mail.de"

[[default_users]]
role = "teacher"
name = "teacher"
password = "1234"
email = "teacher@mail.de"

[[default_users]]
role = "student"
name = "student"
password = "1234"
email = "student@mail.de"

[[exercise_prompts]]
name = "prompt 1"
prompt = """
You will act as a learning assistant. The university student is given this exercise-title: - {title} -
and this task-description: - {description} -
This extracted-pdf was uploaded by the teacher as a theoretical basis for this exercise: - {lesson_file} -
Analyze the answers of the student and give feedback.
"""

[check_conversation_prompt]
prompt = """
"Please check if the answers of the user are serious and if the user answered the original question correctly.
If the user answered the question too short and with too little detail, please ask him to elaborate.
Respond with an explaination of your reasoning.
Your explanation should be in the same language as the user and your explanation should not include any solutions. 
In your explanation you can give hints what is missing in the answer of the user.
If the user did not answer at all, please say that he did not answer.
"""
