check_conversation_prompt = """
Check if the answers of the student answered the exercise correctly.
If the student did not answer correctly, respond with what the errors are but do not give the solution.
If the student answered correctly, you can write one sentence that the student answered correctly and the task is finished.
"""

response_ai_model = "gpt-4.1-mini"

check_ai_model = "gpt-4.1"

how_to_use_text = """
I am your AI tutor and I want to help you understand the content of the lecture. Here's how it works:

1. Explain to me the question I ask you at the beginning of the conversation.
2. When you think the question has been answered – and I also confirm that it has been answered – you can use the "Check Answer" button to verify the conversation. A separate AI will then check whether the task was solved correctly. If the check is successful, you can submit the chat history.

I’m looking forward to working with you!
"""
general_information_text = """
- The AI tutor should only be used for working on the tasks.
- Tutors and professors can view chats that have been submitted.
"""
lecture_information_text = """
# Lecture: Example Lecture XY
- Lecturer: Prof. Dr. Max Mustermann
- Contact: max.mustermann@uni-tuebingen.de
- Content: This lecture is intended to provide an understanding of basic methods and concepts of XY.
"""

course_name = "Example Lecture XY"

[[default_users]]
role = "admin"
name = "admin"
password = "1234"
email = "admin@mail.de"

[[default_users]]
role = "teacher"
name = "teacher"
password = "1234"
email = "teacher@mail.de"

[[default_users]]
role = "student"
name = "student"
password = "1234"
email = "student@mail.de"

[[exercise_prompts]]
name = "learningAssistantPrompt"
prompt = """
You will act as a learning assistant. The university student is given this exercise-title: "{title}"
and this exercise: "{description}"
This is the lesson context uploaded by the teacher as a theoretical basis for this exercise: 

--------------------------
{lesson_context}
--------------------------

The user is a student who has to complete the exercise.
The student will answer the exercise in a conversation with you.
If the student answered the task "{description}" incorrectly, you can give him a hint to help him find the solution but do **not** tell him the solution.
If the student answered the task "{description}" correctly, you will tell him that he is correct and the task is finished.
Do not engage in any other topics than the exercise at hand. If the student asks anything unrelated, tell him that you are only here to help with the exercise.
"""
