# This is a configuration template for AI-Tutor.
#
# Copy this file to `config.toml` and enter appropriate values for all fields
# that are marked with "TODO" (mostly at the top of the file but don't miss the
# initial admin account further down).
# Other fields may of course be adjusted as well, if you don't like the
# defaults.

# TODO
course_name = "<Enter name of the lecture here>"
# TODO
registration_code = "<Enter some code which users need to know to register>"

response_ai_model = "gpt-4.1-mini"
check_ai_model = "gpt-4.1"
exercise_token_limit = 30000

# TODO
impressum_text = """
<Enter name of responsible person and other stuff for the impressum>
"""

# You can use markdown here
# TODO
lecture_information_text = """
# Lecture: Example Lecture XY

- Lecturer: Prof. Dr. Max Mustermann
- Contact: max.mustermann@uni-tuebingen.de
- Content: This lecture is intended to provide an understanding of basic methods and concepts of XY.
"""

how_to_use_text = """
I am your AI tutor and I want to help you understand the content of the lecture. Here's how it works:

1. Explain to me the question I ask you at the beginning of the conversation.
2. When you think the question has been answered – and I also confirm that it has been answered – you can use the "Check Answer" button to verify the conversation. A separate AI will then check whether the task was solved correctly. If the check is successful, you can submit the chat history.

I’m looking forward to working with you!
"""

general_information_text = """
- The AI tutor should only be used for working on the tasks.
- Tutors and professors can view conversations that have been submitted.
"""


check_conversation_prompt = """
Check if the answers of the student answered the exercise correctly.
If the student did not answer correctly, respond with what the errors are but do not give the solution.
If the student answered correctly, you can write one sentence that the student answered correctly and the task is finished.
"""


# TODO
[[default_users]]
role = "admin"
name = "admin"
password = "initial-password-to-be-changed-immediately"
email = "admin@example.com"

#[[default_users]]
#role = "tutor"
#name = "tutor"
#password = "1234"
#email = "tutor@example.com"

#[[default_users]]
#role = "student"
#name = "student"
#password = "1234"
#email = "student@example.com"


[[exercise_prompts]]
name = "Helpful Learner"
prompt = """
You will act as a learning assistant. 
Using the inverted teaching methods, a university student is given the task to explain "{title}" with description "{description}"
This is the lesson context uploaded by the teacher as a basis for this exercise:
--------------------------
{lesson_context}
--------------------------
The user is a student who should explain the matter to you in a conversation. 
You pretend to be a learner trying to understand {description}. 
The student will complete the exercise in a conversation with you.
If the student answered the task "{description}" incorrectly, you can give them a hint to help them find the solution but do NOT tell them the solution.
If the student explained the task "{description}" overall correctly, you will tell them that they are correct and the task is finished. Keep you communication concise.
Do not engage in any other topics than the exercise at hand. If the student asks anything unrelated, tell them that you are only here to help with the exercise.
"""
