"""The state for the finished view page."""

import reflex as rx
from typing import Optional

import aitutor.routes as routes
from aitutor.models import Exercise, ExerciseResult
from aitutor.auth.state import SessionState
from aitutor.pages.chat.state import ChatMessage
from aitutor.global_vars import CHECK_RESULT_ROLE


class FinishedViewState(SessionState):
    """The State for the finished view."""

    messages: list[ChatMessage] = []
    current_exercise: Optional[Exercise] = None
    exercise_title: str = "No Exercise Selected"

    @rx.var
    def chat_url(self) -> str:
        """Returns the URL for the chat page."""
        return routes.CHAT + "/" + str(self.router.page.params.get("exercise_id", 0))

    @rx.event
    def on_load(self):
        """Loads the finished exercise."""
        with rx.session() as session:
            exercise = session.exec(
                Exercise.select().where(Exercise.id == int(self.exercise_id))
            ).one_or_none()
            if exercise:
                self.current_exercise = exercise
                self.exercise_title = exercise.title
                self.messages = []
                self.load_finished_conversation()
            else:
                yield rx.redirect(routes.NOT_FOUND)

    @rx.event
    def delete_submisssion(self):
        """Deletes the submission for the current exercise."""
        userinfo_id: Optional[int] = self.user_id
        if self.current_exercise and userinfo_id:
            with rx.session() as session:
                exercise_result = session.exec(
                    ExerciseResult.select().where(
                        ExerciseResult.exercise_id == self.current_exercise.id,
                        ExerciseResult.userinfo_id == userinfo_id,
                    )
                ).one_or_none()

                if exercise_result:
                    if exercise_result.conversation_text == []:
                        # delete result if no conversation text is present
                        session.delete(exercise_result)
                    else:
                        exercise_result.finished_conversation = []
                    session.commit()
                yield rx.toast.success(
                    title="Submission Deleted",
                    description="Your submission has been deleted successfully.",
                    duration=2500,
                    position="bottom-center",
                    invert=True,
                )
        return rx.redirect(self.chat_url)

    def load_finished_conversation(self):
        """Loads the finished conversation."""
        userinfo_id: Optional[int] = self.user_id
        if self.current_exercise and userinfo_id:
            with rx.session() as session:
                exercise_result = session.exec(
                    ExerciseResult.select().where(
                        ExerciseResult.exercise_id == self.current_exercise.id,
                        ExerciseResult.userinfo_id == userinfo_id,
                    )
                ).one_or_none()

                if exercise_result:
                    for msg in exercise_result.finished_conversation:
                        if msg["role"] in ["user", "assistant", CHECK_RESULT_ROLE]:
                            self.append_chat_message(
                                msg["content"],
                                is_llm=(msg["role"] == "assistant"),
                                is_check_result=(msg["role"] == CHECK_RESULT_ROLE),
                                check_passed=msg.get("check_passed", False),
                            )

    def append_chat_message(
        self,
        message,
        is_llm: bool = False,
        is_check_result: bool = False,
        check_passed: bool = False,
    ):
        """
        Once a new message is generated by the user it is appended to the list of
        messages in ChatState.
        """
        self.messages.append(
            ChatMessage(
                message=message,
                is_llm=is_llm,
                is_check_result=is_check_result,
                check_passed=check_passed,
            )
        )
