"""empty message

Revision ID: 07b6d41b4332
Revises: 87580c97a5c0
Create Date: 2026-09-25 14:08:29.347202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '07b6d41b4332'
down_revision: Union[str, None] = '87580c97a5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaexerciseresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_used', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaexerciseresult', schema=None) as batch_op:
        batch_op.drop_column('tokens_used')

    # ### end Alembic commands ###
