"""Set exercise_id to NULL when exercise is deleted

Revision ID: 0c927ae41592
Revises: 984c654a75a6
Create Date: 2026-01-05 17:54:09.292383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0c927ae41592'
down_revision: Union[str, None] = '984c654a75a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to recreate the table to modify the foreign key constraint
    with op.batch_alter_table('report', schema=None, copy_from=None, recreate='always') as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_report_exercise_id', 'exercise', ['exercise_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_exercise_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercise', ['exercise_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
