"""empty message

Revision ID: 0f247860a023
Revises: 13978d7d4420
Create Date: 2025-11-18 18:16:49.976503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0f247860a023'
down_revision: Union[str, None] = '13978d7d4420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_result_id', sa.Integer(), nullable=False),
    sa.Column('report_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('looked_at', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_result_id'], ['exerciseresult.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
