"""empty message

Revision ID: 19401e204929
Revises: 5dcadaff512f
Create Date: 2026-05-10 11:31:47.435675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '19401e204929'
down_revision: Union[str, None] = '5dcadaff512f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betaexercisetracelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_result_id', sa.Integer(), nullable=False),
    sa.Column('trace_history', sa.JSON(), nullable=True),
    sa.Column('latest_trace', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beta_exercise_result_id'], ['betaexerciseresult.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beta_exercise_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betaexercisetracelog')
    # ### end Alembic commands ###
