"""empty message

Revision ID: 19401e204929
Revises: 5dcadaff512f
Create Date: 2026-05-10 11:31:47.435675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '19401e204929'
down_revision: Union[str, None] = '5dcadaff512f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betaexercisetracelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_result_id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.Column('beta_concept_id', sa.Integer(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('concept_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_entry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beta_exercise_result_id'], ['betaexerciseresult.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['beta_concept_id'], ['betaconcept.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('betaexercisetracelog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_beta_concept_id'), ['beta_concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_beta_exercise_id'), ['beta_exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_beta_exercise_result_id'), ['beta_exercise_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_turn_index'), ['turn_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_userinfo_id'), ['userinfo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaexercisetracelog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_userinfo_id'))
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_turn_index'))
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_beta_exercise_result_id'))
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_beta_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_beta_concept_id'))

    op.drop_table('betaexercisetracelog')
    # ### end Alembic commands ###
