"""empty message

Revision ID: 1fe016694cca
Revises: 6a026486ef4f
Create Date: 2026-05-13 18:26:39.506971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1fe016694cca'
down_revision: Union[str, None] = '6a026486ef4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaexerciseresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_conversation', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('completion_unlocked', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('submit_time_stamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaexerciseresult', schema=None) as batch_op:
        batch_op.drop_column('submit_time_stamp')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('completion_unlocked')
        batch_op.drop_column('finished_conversation')

    # ### end Alembic commands ###
