"""empty message

Revision ID: 208f54325bba
Revises: ce38a062081b
Create Date: 2026-07-06 21:57:14.566494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208f54325bba'
down_revision: Union[str, None] = 'ce38a062081b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can interfere with table rebuilds.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'exercise',
        schema=None,
        naming_convention={'uq': 'uq_%(table_name)s_%(column_0_name)s'},
    ) as batch_op:
        batch_op.drop_constraint('uq_exercise_title', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can interfere with table rebuilds.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_exercise_title', ['title'])

    # ### end Alembic commands ###
