"""empty message

Revision ID: 28b4764b10e9
Revises: 19401e204929
Create Date: 2026-05-10 11:54:25.539378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '28b4764b10e9'
down_revision: Union[str, None] = '19401e204929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betastudentconceptstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('beta_concept_id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts_total', sa.Integer(), nullable=False),
    sa.Column('successful_attempts', sa.Integer(), nullable=False),
    sa.Column('misconception_hits', sa.Integer(), nullable=False),
    sa.Column('last_diagnosis_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_policy_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beta_concept_id'], ['betaconcept.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betastudentconceptstate')
    # ### end Alembic commands ###
