"""empty message

Revision ID: 2bb24f0c0869
Revises: 4f7197e7ac5d
Create Date: 2025-05-06 13:32:00.075512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2bb24f0c0869'
down_revision: Union[str, None] = '4f7197e7ac5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('userinfo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
        batch_op.alter_column('userinfo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
