"""empty message

Revision ID: 2ec3a5b6e9c0
Revises: 28b4764b10e9
Create Date: 2026-05-10 12:36:19.232810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2ec3a5b6e9c0'
down_revision: Union[str, None] = '28b4764b10e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betastudentconceptstate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('covered_core_point_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('missing_core_point_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('evidence_by_core_point', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betastudentconceptstate', schema=None) as batch_op:
        batch_op.drop_column('evidence_by_core_point')
        batch_op.drop_column('missing_core_point_ids')
        batch_op.drop_column('covered_core_point_ids')

    # ### end Alembic commands ###
