"""Add is_default_prompt flag to prompt table.

Revision ID: 2eff6b4c1532
Revises: 8bbdf93d638d
Create Date: 2026-01-21 14:56:23.533128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2eff6b4c1532'
down_revision: Union[str, None] = '8bbdf93d638d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Need to disable foreign key constraints for SQLite (otherwise altering table
    # fails).  See https://alembic.sqlalchemy.org/en/latest/batch.html
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default_prompt', sa.Boolean(), server_default=sa.sql.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Need to disable foreign key constraints for SQLite (otherwise altering table
    # fails).  See https://alembic.sqlalchemy.org/en/latest/batch.html
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('is_default_prompt')

    # ### end Alembic commands ###
