"""empty message

Revision ID: 38ab9eec608b
Revises: dc622bd84e30
Create Date: 2026-05-30 12:52:20.441977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '38ab9eec608b'
down_revision: Union[str, None] = 'dc622bd84e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betastudentconceptstate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_misconceptions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('resolved_misconceptions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betastudentconceptstate', schema=None) as batch_op:
        batch_op.drop_column('resolved_misconceptions')
        batch_op.drop_column('active_misconceptions')

    # ### end Alembic commands ###
