"""empty message

Revision ID: 3b1567ad9091
Revises: a11f76f385d6
Create Date: 2025-08-27 12:42:58.855452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3b1567ad9091'
down_revision: Union[str, None] = 'a11f76f385d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('days_to_complete', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('days_to_complete')
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
