"""empty message

Revision ID: 472b6c5cdb6b
Revises: e7ea766e2236
Create Date: 2025-05-26 17:27:51.126816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '472b6c5cdb6b'
down_revision: Union[str, None] = 'e7ea766e2236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('lesson_file')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_file', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('lesson_context')

    # ### end Alembic commands ###
