"""empty message

Revision ID: 4e51f030b911
Revises: 208f54325bba
Create Date: 2026-07-20 13:24:04.047035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4e51f030b911"
down_revision: Union[str, None] = "208f54325bba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lecture_id", sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_tag_name"))
        batch_op.create_index(batch_op.f("ix_tag_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tag_lecture_id"), ["lecture_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_tag_lecture_id_lecture",
            "lecture",
            ["lecture_id"],
            ["id"],
            ondelete="CASCADE",
        )


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_constraint("fk_tag_lecture_id_lecture", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_tag_lecture_id"))
        batch_op.drop_index(batch_op.f("ix_tag_name"))
        batch_op.create_index(batch_op.f("ix_tag_name"), ["name"], unique=True)
        batch_op.drop_column("lecture_id")

    # ### end Alembic commands ###
