"""empty message

Revision ID: 4fd21c245fcd
Revises: 985c806b1347
Create Date: 2026-03-14 18:43:24.482884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4fd21c245fcd'
down_revision: Union[str, None] = '985c806b1347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('LECTURER', 'MAINTAINER', 'ADMIN', name='globalrole'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['localuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # datamigration: assign all current ADMINs the global ADMIN role
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        INSERT INTO permission (user_id, permission)
        SELECT user_id, 'ADMIN' 
        FROM userinfo 
        WHERE role = 'ADMIN'
        """)
    )

    # rename ADMIN to OWNER in userinfo table
    connection.execute(
        sa.text("""
        UPDATE userinfo
        SET role = 'OWNER'
        WHERE role = 'ADMIN'
        """)
    )

def downgrade() -> None:
    """Downgrade schema."""
    # rename OWNER back to ADMIN in userinfo table
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE userinfo SET role = 'ADMIN' WHERE role = 'OWNER'")
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_user_id'))

    op.drop_table('permission')
    # ### end Alembic commands ###
