"""empty message

Revision ID: 4fd9d759d0f7
Revises: 98ca1037a63e
Create Date: 2026-02-17 21:48:29.392865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4fd9d759d0f7'
down_revision: Union[str, None] = '98ca1037a63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_sqlite = conn.engine.name.startswith("sqlite")

    try:
        if is_sqlite:
            conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

        with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    'tokens_used',
                    sa.Integer(),
                    server_default=sa.text('0'),
                    nullable=False,
                )
            )
    finally:
        if is_sqlite:
            conn.execute(sa.text("PRAGMA foreign_keys=ON"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_sqlite = conn.engine.name.startswith("sqlite")

    try:
        if is_sqlite:
            conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

        with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
            batch_op.drop_column('tokens_used')
    finally:
        if is_sqlite:
            conn.execute(sa.text("PRAGMA foreign_keys=ON"))

    # ### end Alembic commands ###
