"""empty message

Revision ID: 58834e03684f
Revises: cce41a34a7fa
Create Date: 2026-05-03 17:22:16.118386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '58834e03684f'
down_revision: Union[str, None] = 'cce41a34a7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_conversation_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecture_information_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecture_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecturer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lecture_name')
    )
    op.create_table('linkuserlecture',
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TUTOR', 'OWNER', name='lecturerole'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['localuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lecture_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkuserlecture')
    op.drop_table('lecture')
    # ### end Alembic commands ###
