"""empty message

Revision ID: 5c9383ae2ef1
Revises: bfd6aa9f8151
Create Date: 2025-05-09 20:08:57.015489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5c9383ae2ef1'
down_revision: Union[str, None] = 'bfd6aa9f8151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_name', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('prompt_name')

    # ### end Alembic commands ###
