"""empty message

Revision ID: 5dcadaff512f
Revises: f53b8dfe43b7
Create Date: 2026-05-10 11:07:27.359035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5dcadaff512f'
down_revision: Union[str, None] = 'f53b8dfe43b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betaexerciseresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_text', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betaexerciseresult')
    # ### end Alembic commands ###
