"""empty message

Revision ID: 66420570a9e3
Revises: 0ce810c7ed80
Create Date: 2026-10-01 00:23:05.969581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '66420570a9e3'
down_revision: Union[str, None] = '0ce810c7ed80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betaexercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_material_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_material_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('days_to_complete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], name=op.f('fk_betaexercise_lecture_id_lecture'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_betaexercise')),
    sa.UniqueConstraint('lecture_id', 'title', name='uq_betaexercise_lecture_id_title')
    )
    with op.batch_alter_table('betaexercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betaexercise_lecture_id'), ['lecture_id'], unique=False)

    op.create_table('betaconcept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], name=op.f('fk_betaconcept_beta_exercise_id_betaexercise'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_betaconcept'))
    )
    with op.batch_alter_table('betaconcept', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betaconcept_concept_id'), ['concept_id'], unique=False)

    op.create_table('betaexerciseresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_text', sa.JSON(), nullable=True),
    sa.Column('finished_conversation', sa.JSON(), nullable=True),
    sa.Column('completion_unlocked', sa.Boolean(), nullable=False),
    sa.Column('analysis_allowed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submit_time_stamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], name=op.f('fk_betaexerciseresult_beta_exercise_id_betaexercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], name=op.f('fk_betaexerciseresult_userinfo_id_userinfo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_betaexerciseresult'))
    )
    op.create_table('betaexercisetaglink',
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], name=op.f('fk_betaexercisetaglink_beta_exercise_id_betaexercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_betaexercisetaglink_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beta_exercise_id', 'tag_id', name=op.f('pk_betaexercisetaglink'))
    )
    op.create_table('betacorepoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_concept_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_concept_id'], ['betaconcept.id'], name=op.f('fk_betacorepoint_beta_concept_id_betaconcept'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_betacorepoint'))
    )
    op.create_table('betaexercisetracelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_result_id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.Column('beta_concept_id', sa.Integer(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('concept_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_entry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beta_concept_id'], ['betaconcept.id'], name=op.f('fk_betaexercisetracelog_beta_concept_id_betaconcept'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], name=op.f('fk_betaexercisetracelog_beta_exercise_id_betaexercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['beta_exercise_result_id'], ['betaexerciseresult.id'], name=op.f('fk_betaexercisetracelog_beta_exercise_result_id_betaexerciseresult'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], name=op.f('fk_betaexercisetracelog_userinfo_id_userinfo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_betaexercisetracelog'))
    )
    with op.batch_alter_table('betaexercisetracelog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_beta_concept_id'), ['beta_concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_beta_exercise_id'), ['beta_exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_beta_exercise_result_id'), ['beta_exercise_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_turn_index'), ['turn_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_betaexercisetracelog_userinfo_id'), ['userinfo_id'], unique=False)

    op.create_table('betamisconception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_concept_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_concept_id'], ['betaconcept.id'], name=op.f('fk_betamisconception_beta_concept_id_betaconcept'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_betamisconception'))
    )
    op.create_table('betastudentconceptstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('beta_concept_id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts_total', sa.Integer(), nullable=False),
    sa.Column('successful_attempts', sa.Integer(), nullable=False),
    sa.Column('misconception_hits', sa.Integer(), nullable=False),
    sa.Column('covered_core_point_ids', sa.JSON(), nullable=True),
    sa.Column('missing_core_point_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_by_core_point', sa.JSON(), nullable=True),
    sa.Column('level_status', sa.JSON(), nullable=True),
    sa.Column('level_evidence', sa.JSON(), nullable=True),
    sa.Column('active_misconceptions', sa.JSON(), nullable=True),
    sa.Column('resolved_misconceptions', sa.JSON(), nullable=True),
    sa.Column('last_diagnosis_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_policy_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beta_concept_id'], ['betaconcept.id'], name=op.f('fk_betastudentconceptstate_beta_concept_id_betaconcept'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], name=op.f('fk_betastudentconceptstate_beta_exercise_id_betaexercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], name=op.f('fk_betastudentconceptstate_userinfo_id_userinfo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_betastudentconceptstate'))
    )
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_ai_model', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'gpt-4.1'"), nullable=False))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beta_exercise_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exercise_type', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'alpha'"), nullable=False))
        batch_op.create_foreign_key('fk_report_beta_exercise_id', 'betaexercise', ['beta_exercise_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_beta_exercise_id', type_='foreignkey')
        batch_op.drop_column('exercise_type')
        batch_op.drop_column('beta_exercise_id')

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('level_ai_model')

    op.drop_table('betastudentconceptstate')
    op.drop_table('betamisconception')
    with op.batch_alter_table('betaexercisetracelog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_userinfo_id'))
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_turn_index'))
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_beta_exercise_result_id'))
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_beta_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_betaexercisetracelog_beta_concept_id'))

    op.drop_table('betaexercisetracelog')
    op.drop_table('betacorepoint')
    op.drop_table('betaexercisetaglink')
    op.drop_table('betaexerciseresult')
    with op.batch_alter_table('betaconcept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betaconcept_concept_id'))

    op.drop_table('betaconcept')
    with op.batch_alter_table('betaexercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betaexercise_lecture_id'))

    op.drop_table('betaexercise')
    # ### end Alembic commands ###
