"""empty message

Revision ID: 69ed9eeebd33
Revises: 3b1567ad9091
Create Date: 2025-09-11 11:42:22.087529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '69ed9eeebd33'
down_revision: Union[str, None] = '3b1567ad9091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

LanguageEnum = sa.Enum('EN', 'DE', name='language')


def upgrade() -> None:
    """Upgrade schema."""
    LanguageEnum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', LanguageEnum, nullable=False, server_default='EN'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_column('language')
    # ### end Alembic commands ###
    LanguageEnum.drop(op.get_bind(), checkfirst=True)
