"""empty message

Revision ID: 6a026486ef4f
Revises: 2ec3a5b6e9c0
Create Date: 2026-05-10 20:52:39.986057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6a026486ef4f'
down_revision: Union[str, None] = '2ec3a5b6e9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betastudentconceptstate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_status', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('level_evidence', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betastudentconceptstate', schema=None) as batch_op:
        batch_op.drop_column('level_evidence')
        batch_op.drop_column('level_status')

    # ### end Alembic commands ###
