"""empty message

Revision ID: 6b2913a0f89b
Revises: 6b9674012543
Create Date: 2026-09-13 19:59:25.018353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6b2913a0f89b'
down_revision: Union[str, None] = '6b9674012543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaexercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_betaexercise_title'), type_='unique')
        batch_op.create_index(batch_op.f('ix_betaexercise_lecture_id'), ['lecture_id'], unique=False)
        batch_op.create_unique_constraint('uq_betaexercise_lecture_id_title', ['lecture_id', 'title'])
        batch_op.create_foreign_key(batch_op.f('fk_betaexercise_lecture_id_lecture'), 'lecture', ['lecture_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaexercise', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_betaexercise_lecture_id_lecture'), type_='foreignkey')
        batch_op.drop_constraint('uq_betaexercise_lecture_id_title', type_='unique')
        batch_op.drop_index(batch_op.f('ix_betaexercise_lecture_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_betaexercise_title'), ['title'])
        batch_op.drop_column('lecture_id')

    # ### end Alembic commands ###
