"""empty message

Revision ID: 87580c97a5c0
Revises: 6b2913a0f89b
Create Date: 2026-09-20 18:06:43.789740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '87580c97a5c0'
down_revision: Union[str, None] = '6b2913a0f89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betaexercisetaglink',
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], name=op.f('fk_betaexercisetaglink_beta_exercise_id_betaexercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_betaexercisetaglink_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beta_exercise_id', 'tag_id', name=op.f('pk_betaexercisetaglink'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betaexercisetaglink')
    # ### end Alembic commands ###
