"""add_banner_to_config

Revision ID: 88396a0d3bb1
Revises: 208f54325bba
Create Date: 2026-08-08 13:25:53.003311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '88396a0d3bb1'
down_revision: Union[str, None] = '9ba4232eeb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Need to disable foreign key constraints for SQLite.  SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_message', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('banner_message_type', sa.Enum('info', 'warning', 'error', 'success', name='bannermessagetype'), server_default=sa.text("'info'"), nullable=False))
        batch_op.add_column(sa.Column('banner_is_open', sa.Boolean(), server_default=sa.sql.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Need to disable foreign key constraints for SQLite.  SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('banner_is_open')
        batch_op.drop_column('banner_message_type')
        batch_op.drop_column('banner_message')

    # ### end Alembic commands ###
