"""add_banner_to_config

Revision ID: 88396a0d3bb1
Revises: 208f54325bba
Create Date: 2026-08-08 13:25:53.003311

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88396a0d3bb1"
down_revision: Union[str, None] = "9ba4232eeb54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

banner_message_type_enum = sa.Enum(
    "INFO",
    "WARNING",
    "ERROR",
    "SUCCESS",
    name="bannermessagetype",
)


def upgrade() -> None:
    """Upgrade schema."""
    # Need to disable foreign key constraints for SQLite.  SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    banner_message_type_enum.create(conn, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "banner_message",
                sqlmodel.sql.sqltypes.AutoString(),
                server_default=sa.text("('')"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "banner_message_type",
                banner_message_type_enum,
                server_default=sa.text("'INFO'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "banner_is_open",
                sa.Boolean(),
                server_default=sa.sql.false(),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Need to disable foreign key constraints for SQLite.  SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.drop_column("banner_is_open")
        batch_op.drop_column("banner_message_type")
        batch_op.drop_column("banner_message")

    banner_message_type_enum.drop(conn, checkfirst=True)

    # ### end Alembic commands ###
