"""make email unique

Revision ID: 920af09cb897
Revises: 0ce810c7ed80
Create Date: 2026-09-21 10:56:10.374762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920af09cb897'
down_revision: Union[str, None] = '0ce810c7ed80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # minimal table structure for data inspection
    userinfo_table = sa.Table(
        "userinfo",
        sa.MetaData(),
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("email", sa.String, nullable=False),
    )

    duplicates = bind.execute(
        sa.select(userinfo_table.c.email)
        .group_by(userinfo_table.c.email)
        .having(sa.func.count(userinfo_table.c.id) > 1)
    ).scalars().all()

    if duplicates:
        raise RuntimeError(
            "Cannot make userinfo.email unique: duplicate emails found for "
            f"{duplicates}. Resolve these manually before rerunning this migration."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_userinfo_email'), ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_userinfo_email'), type_='unique')

    # ### end Alembic commands ###
