"""empty message

Revision ID: 985c806b1347
Revises: 4fd9d759d0f7
Create Date: 2026-02-23 22:26:10.260973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '985c806b1347'
down_revision: Union[str, None] = '4fd9d759d0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_token_limit', sa.Integer(), server_default=sa.text('(30000)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('exercise_token_limit')

    # ### end Alembic commands ###
