"""empty message

Revision ID: 98ca1037a63e
Revises: 2eff6b4c1532
Create Date: 2026-02-09 13:48:24.475055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ca1037a63e'
down_revision: Union[str, None] = '2eff6b4c1532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # minimal table structure for data manipulation
    exercise_table = sa.Table(
        "exercise",
        sa.MetaData(),
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("title", sa.String, nullable=False),
    )

    results = bind.execute(sa.select(exercise_table.c.id, exercise_table.c.title)).all()

    title_counts = {}

    for row in results:
        title = row.title
        ex_id = row.id

        if title in title_counts:
            # Duplicate found, increment counter and rename
            title_counts[title] += 1
            new_title = f"{title}_{title_counts[title]}"
            
            bind.execute(
                exercise_table.update()
                .where(exercise_table.c.id == ex_id)
                .values(title=new_title)
            )
        else:
            # First occurrence
            title_counts[title] = 1

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_exercise_title", ['title'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint("uq_exercise_title", type_='unique')

    # ### end Alembic commands ###
