"""Migration after adding naming conventions for constraints/indices.

Revision ID: 9ba4232eeb54
Revises: dc5a36ddd68a
Create Date: 2026-08-12 16:43:20.338148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba4232eeb54'
down_revision: Union[str, None] = 'dc5a36ddd68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('only_one_row'), type_='check')
        batch_op.create_check_constraint(batch_op.f('ck_config_`only_one_row`'), 'id = 1')

    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_lecture_lecture_name'), ['lecture_name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_lecture_lecture_name'), type_='unique')

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_config_`only_one_row`'), type_='check')
        batch_op.create_check_constraint(batch_op.f('only_one_row'), 'id = 1')

    # ### end Alembic commands ###
