"""empty message

Revision ID: a11f76f385d6
Revises: 47505b705585
Create Date: 2025-07-20 12:01:45.599054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a11f76f385d6'
down_revision: Union[str, None] = '47505b705585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercisetaglink',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'tag_id')
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sqlite.JSON(), nullable=True))

    op.drop_table('exercisetaglink')
    # ### end Alembic commands ###
