"""add is_default_prompt flag to prompt table

Revision ID: a9ef0a67974f
Revises: 984c654a75a6
Create Date: 2026-01-10 18:31:44.280257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a9ef0a67974f'
down_revision: Union[str, None] = '984c654a75a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default_prompt', sa.Boolean(), server_default=sa.sql.false, nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('is_default_prompt')

    # ### end Alembic commands ###
