"""empty message

Revision ID: b427112eca4e
Revises: 472b6c5cdb6b
Create Date: 2025-05-30 17:28:22.964785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b427112eca4e'
down_revision: Union[str, None] = '472b6c5cdb6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_time_stamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('time_stamp')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', sa.DATETIME(), nullable=False))
        batch_op.drop_column('submit_time_stamp')

    # ### end Alembic commands ###
