"""empty message

Revision ID: b54bd38711ed
Revises: 208f54325bba
Create Date: 2026-08-03 15:17:12.639250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b54bd38711ed'
down_revision: Union[str, None] = '208f54325bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can interfere with table rebuilds.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('lecture_information_text')
        batch_op.drop_column('check_conversation_prompt')
        batch_op.drop_column('course_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can interfere with table rebuilds.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('check_conversation_prompt', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('lecture_information_text', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
