"""empty message

Revision ID: bf1716aeb859
Revises: 13978d7d4420
Create Date: 2025-11-09 13:53:00.148824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf1716aeb859'
down_revision: Union[str, None] = '13978d7d4420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_conversation_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_ai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_ai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('how_to_use_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('general_information_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecture_information_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('impressum_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('id = 1', name='only_one_row'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ###
