"""empty message

Revision ID: bfd6aa9f8151
Revises: 0cb56d22ab40
Create Date: 2025-05-06 15:56:59.672304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bfd6aa9f8151'
down_revision: Union[str, None] = '0cb56d22ab40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
