"""Add lecturer-registration-token table

Revision ID: c08f4cb20e72
Revises: 9ba4232eeb54
Create Date: 2026-08-14 10:00:18.566507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c08f4cb20e72'
down_revision: Union[str, None] = '9ba4232eeb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturerregistrationtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['localuser.id'], name=op.f('fk_lecturerregistrationtoken_created_by_localuser'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecturerregistrationtoken')),
    sa.UniqueConstraint('token', name=op.f('uq_lecturerregistrationtoken_token'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturerregistrationtoken')
    # ### end Alembic commands ###
