"""empty message

Revision ID: c9782a9331d4
Revises: df4ec81ec5d5
Create Date: 2026-05-25 17:27:28.225103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c9782a9331d4'
down_revision: Union[str, None] = 'df4ec81ec5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_exercise_lecture_id'), ['lecture_id'], unique=False)
        batch_op.create_foreign_key('fk_exercise_lecture_id_lecture', 'lecture', ['lecture_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exercise_lecture_id_lecture', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exercise_lecture_id'))
        batch_op.drop_column('lecture_id')

    # ### end Alembic commands ###
