"""empty message

Revision ID: cce41a34a7fa
Revises: 985c806b1347
Create Date: 2026-03-25 12:13:06.576767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cce41a34a7fa'
down_revision: Union[str, None] = '985c806b1347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('LECTURER', 'MAINTAINER', 'ADMIN', name='globalpermission'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['localuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # datamigration: assign all current ADMINs the global ADMIN role
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        INSERT INTO permission (user_id, permission)
        SELECT user_id, 'ADMIN' 
        FROM userinfo 
        WHERE role = 'ADMIN'
        """)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_user_id'))

    op.drop_table('permission')
    # ### end Alembic commands ###