"""empty message

Revision ID: ce38a062081b
Revises: b47709e94562
Create Date: 2026-06-23 00:19:43.552344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ce38a062081b'
down_revision: Union[str, None] = 'b47709e94562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can interfere with table rebuilds.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_prompt_id', sa.Integer(), nullable=True))

    with op.batch_alter_table(
        'prompt',
        schema=None,
        naming_convention={'uq': 'uq_%(table_name)s_%(column_0_name)s'},
    ) as batch_op:
        batch_op.drop_constraint('uq_prompt_name', type_='unique')
        batch_op.add_column(sa.Column('lecture_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prompt_lecture_id'), ['lecture_id'], unique=False)
        batch_op.create_foreign_key('fk_prompt_lecture_id_lecture', 'lecture', ['lecture_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Need to disable foreign key constraints for SQLite. SQLite recreates tables
    # for batch alters, and active foreign keys can interfere with table rebuilds.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prompt_lecture_id_lecture', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prompt_lecture_id'))
        batch_op.drop_column('lecture_id')
        batch_op.create_unique_constraint('uq_prompt_name', ['name'])

    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.drop_column('default_prompt_id')

    # ### end Alembic commands ###
