"""empty message

Revision ID: d01d31ae6887
Revises: 821fd6ad778b
Create Date: 2024-12-03 16:03:56.840521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd01d31ae6887'
down_revision: Union[str, None] = '821fd6ad778b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authsession', schema=None) as batch_op:
        batch_op.drop_index('ix_authsession_session_id')
        batch_op.drop_index('ix_authsession_user_id')

    op.drop_table('authsession')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    op.create_table('authsession',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('expiration', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authsession', schema=None) as batch_op:
        batch_op.create_index('ix_authsession_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_authsession_session_id', ['session_id'], unique=1)

    # ### end Alembic commands ###
