"""empty message

Revision ID: dfc4c7614613
Revises: 58834e03684f
Create Date: 2026-05-05 18:17:55.295757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dfc4c7614613'
down_revision: Union[str, None] = '58834e03684f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betaexercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_material_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_material_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('days_to_complete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('betaconcept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_exercise_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_exercise_id'], ['betaexercise.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('betaconcept', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betaconcept_concept_id'), ['concept_id'], unique=False)

    op.create_table('betacorepoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_concept_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_concept_id'], ['betaconcept.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betamisconception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beta_concept_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beta_concept_id'], ['betaconcept.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betamisconception')
    op.drop_table('betacorepoint')
    with op.batch_alter_table('betaconcept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betaconcept_concept_id'))

    op.drop_table('betaconcept')
    op.drop_table('betaexercise')
    # ### end Alembic commands ###
