"""Add email verification

Revision ID: e4c7a1b90f32
Revises: 0ce810c7ed80
Create Date: 2026-09-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e4c7a1b90f32'
down_revision: Union[str, None] = '0ce810c7ed80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Need to disable foreign key constraints for SQLite.  SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    op.create_table('verificationtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL', 'PASSWORD_RESET', name='verificationpurpose'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['localuser.id'], name=op.f('fk_verificationtoken_user_id_localuser'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verificationtoken')),
    sa.UniqueConstraint('user_id', 'purpose', name='uq_verificationtoken_user_id_purpose')
    )
    with op.batch_alter_table('verificationtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verificationtoken_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_verificationtoken_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), server_default=sa.sql.false(), nullable=False))
        # added as nullable here, see data migration below
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###

    # datamigration: All accounts that exist at this point were created before email
    # verification was introduced, so they must be marked as verified.  Otherwise
    # nobody would be able to log in anymore (and the cleanup job for unverified
    # accounts would eventually delete all of them).
    #
    # The exact creation time of those accounts is unknown, so fall back to "now".
    # This is only safe in combination with the verified=TRUE above: the cleanup job
    # only ever considers accounts that are *not* verified.
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE userinfo SET verified = TRUE, created_at = CURRENT_TIMESTAMP")
    )

    # now that every row has a value, created_at can be made non-nullable
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at', existing_type=sa.DateTime(timezone=True), nullable=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Need to disable foreign key constraints for SQLite.  SQLite recreates tables
    # for batch alters, and active foreign keys can trigger cascaded deletes.
    conn = op.get_bind()
    if conn.engine.name.startswith("sqlite"):
        conn.execute(sa.text("PRAGMA foreign_keys=OFF"))

    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('verified')

    with op.batch_alter_table('verificationtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verificationtoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_verificationtoken_token_hash'))

    op.drop_table('verificationtoken')
    # ### end Alembic commands ###
