"""empty message

Revision ID: e7f67ded3d82
Revises: 2b9639533bf3
Create Date: 2025-05-05 17:51:02.706911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e7f67ded3d82'
down_revision: Union[str, None] = '2b9639533bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
        batch_op.alter_column('userinfo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseresult', schema=None) as batch_op:
        batch_op.alter_column('userinfo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
