"""empty message

Revision ID: f802b1b017d6
Revises: fd654871fd97
Create Date: 2026-09-30 23:53:40.136321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f802b1b017d6'
down_revision: Union[str, None] = 'fd654871fd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betacorepoint', schema=None) as batch_op:
        batch_op.drop_column('required')

    with op.batch_alter_table('betaexerciseresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_allowed', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaexerciseresult', schema=None) as batch_op:
        batch_op.drop_column('analysis_allowed')

    with op.batch_alter_table('betacorepoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
