"""empty message

Revision ID: fd654871fd97
Revises: 07b6d41b4332
Create Date: 2026-09-25 15:48:09.328221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fd654871fd97'
down_revision: Union[str, None] = '07b6d41b4332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beta_exercise_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exercise_type', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'alpha'"), nullable=False))
        batch_op.create_foreign_key('fk_report_beta_exercise_id', 'betaexercise', ['beta_exercise_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_beta_exercise_id', type_='foreignkey')
        batch_op.drop_column('exercise_type')
        batch_op.drop_column('beta_exercise_id')

    # ### end Alembic commands ###
