"""empty message

Revision ID: fe212a82e125
Revises: af601f170731
Create Date: 2025-12-01 12:10:45.279767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fe212a82e125'
down_revision: Union[str, None] = 'af601f170731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # 1. Add the new column (nullable initially)
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_id', sa.Integer(), nullable=True))

    # 2. DATA MIGRATION: Update prompt_id based on the existing prompt_name
    # This SQL query works for SQLite and PostgreSQL.
    # It sets prompt_id to the id found in the prompt table where names match.
    bind.execute(sa.text(
        """
        UPDATE exercise
        SET prompt_id = (
            SELECT id 
            FROM prompt 
            WHERE prompt.name = exercise.prompt_name
        )
        """
    ))

    # 3. Create FK constraint and drop old columns
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_exercise_prompt_id', 'prompt', ['prompt_id'], ['id'])
        
        batch_op.drop_column('prompt')
        batch_op.drop_column('prompt_name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_name', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('prompt', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_exercise_prompt_id', type_='foreignkey')
        batch_op.drop_column('prompt_id')

    # ### end Alembic commands ###
