"""This module contains the chat component."""

import reflex as rx
import asyncio

from aitandem.pages.login import require_login


class ChatMessage(rx.Base):
    """
    Class to make handling ChatMessages easier and help differentiate between authors of
    chat messages.
    """

    message: str
    is_llm: bool = False


class ChatState(rx.State):
    """Handles the ChatState."""

    messages: list[ChatMessage] = []  # Used to display the conversation so far.
    did_submit: bool = False

    @rx.var
    def user_did_submit(self) -> bool:
        """ """
        return self.did_submit

    def append_chat_message(self, message, is_llm: bool = False):
        """
        Once a new message is generated by the user it is appended to the list of
        messages in ChatState.
        """
        self.messages.append(ChatMessage(message=message, is_llm=is_llm))

    async def handle_chat_submit(self, form_data: dict):
        """
        New messages get appended to list of ChatMessages.
        """
        print("here is your form data: ", form_data)
        user_messsage = form_data.get("user_response")
        if user_messsage:
            self.did_submit = True
            self.append_chat_message(message=user_messsage, is_llm=False)
            yield
            await asyncio.sleep(2)
            self.did_submit = False
            self.append_chat_message(message=user_messsage, is_llm=True)
            yield


# Message_style template for Markdown from Reflex
message_style = dict(
    display="inline-block",
    padding="1em",
    border_radius="8px",
    max_width=["30em", "30em", "50em", "50em", "50em", "50em"],
)


def message_box(chat_message: ChatMessage) -> rx.Component:
    """Each message from the chat history gets its bounding box. Depending on the sender
    the message is aligned to the left for the LLM and aligned to the right for the user
    .
    """
    return rx.box(
        rx.box(
            rx.markdown(
                chat_message.message,
                background_color=rx.cond(
                    chat_message.is_llm, rx.color("mauve", 4), rx.color("blue", 4)
                ),
                color=rx.cond(
                    chat_message.is_llm, rx.color("mauve", 12), rx.color("blue", 12)
                ),
                **message_style,
            ),
            text_align=rx.cond(chat_message.is_llm, "left", "right"),
            margin_top="1em",
        ),
        width="100%",
    )


def chat_form() -> rx.Component:
    """
    Render the chat form for user input. Includes button to send Reply and button to
    check the answer.
    """
    return rx.form(
        rx.vstack(
            rx.text_area(
                name="user_response",
                placeholder="Your Answer",
                required=True,
                width="100%",
            ),
            rx.hstack(
                rx.button("Submit", type="submit"),
                rx.cond(ChatState.did_submit, rx.text("Reply sent!"), rx.fragment()),
                # rx.fragment() is placeholder for now
                rx.button("Check Answer", type="submit"),
            ),
        ),
        on_submit=ChatState.handle_chat_submit,
        reset_on_submit=True,
    )

@require_login()
def chat_default() -> rx.Component:
    """Renders the web page."""
    return rx.container(
        rx.box(
            rx.vstack(
                rx.heading("Exercise number i!", size="5"),
                rx.box(
                    rx.foreach(ChatState.messages, message_box),
                    width="100%",
                    overflow="auto",  # Chat history becomes scrollable
                    max_height="60vh",
                    padding_right="8px",
                ),
                chat_form(),
                spacing="5",
                justify="center",
                min_height="15vh",
            ),
            width="100%",
        ),
        width="100%",
    )
