"""This module contains the chat component."""

import reflex as rx
from decouple import config
from openai import AsyncOpenAI

DEFAULT_MODEL = "gpt-4o-mini"


async def get_response(conversation):
    """
    Sends asynchronous requests to OpenAI.

    conversation: Expects list of dictionaries of the previous messages between ChatGPT
    and the user.
    """
    # I use python decouple to retrive the API Key, can also use os.
    API_KEY = config("OPENAI_API_KEY", cast=str, default=None)
    if not API_KEY:
        raise ValueError("API key not found.")
    # Creates GPT instance
    client = AsyncOpenAI(api_key=API_KEY)
    # Wait till Chat Completion Request is fulfilled.
    session = await client.chat.completions.create(
        model=DEFAULT_MODEL, messages=conversation
    )
    # Extracts the first response by CHATGPT. By default only a single response is
    # generated.
    response = session.choices[0].message.content
    if not isinstance(response, str):
        raise TypeError(f"Expected string but got {type(response)}: {response}")
    return response


class ChatMessage(rx.Base):
    """
    Class to make handling ChatMessages easier and help differentiate between authors of
    chat messages.
    """

    message: str
    is_llm: bool = False


class ChatState(rx.State):
    """Handles the ChatState."""

    messages: list[ChatMessage] = []  # Used to display the conversation so far.
    did_submit: bool = False

    @rx.var
    def user_did_submit(self) -> bool:
        """ """
        return self.did_submit

    def append_chat_message(self, message, is_llm: bool = False):
        """
        Once a new message is generated by the user it is appended to the list of
        messages in ChatState.
        """
        self.messages.append(ChatMessage(message=message, is_llm=is_llm))

    async def handle_chat_submit(self, form_data: dict):
        """
        New messages get appended to list of ChatMessages.
        """
        # Can be used for debugging
        # print("here is your form data: ", form_data)
        user_messsage = form_data.get("user_response")
        if user_messsage:
            self.did_submit = True
            self.append_chat_message(message=user_messsage, is_llm=False)
            yield
            self.did_submit = False
            # Takes list of ChatMessage and turns into a list of dictionaries, so the
            # OpenAI API can handle the messages.
            messages = self.get_messages_dict_gpt()
            # Wait while OpenAI Response is generated.
            llm_response = await get_response(conversation=messages)
            # Append response generated by LLM to list of messages, set is_llm to True
            # to indicate that it is generated by the user.
            self.append_chat_message(message=llm_response, is_llm=True)
            yield

    def get_messages_dict_gpt(self):
        """
        This functions iterates over all previous chat messages and reformats them as a
        list of dicitonaries, so they can be handed to the OpenAI-API.
        """
        # Initialize GPT with the desired role, for now GPT acts as a generic tutor.
        # TODO Initialization should change depending on the exercises.
        messages_gpt = [
            {
                "role": "system",
                "content": "You are a tutor verifying explanations to various topics.",
            }
        ]
        # Iterate through all message, create dictionary for each message and append
        # them to list of dictionaries.
        for chat_message in self.messages:
            role = "user"
            if chat_message.is_llm:
                role = "assistant"
            messages_gpt.append({"role": role, "content": chat_message.message})
        return messages_gpt


# Message_style template for Markdown from Reflex
message_style = dict(
    display="inline-block",
    padding="1em",
    border_radius="8px",
    max_width=["30em", "30em", "50em", "50em", "50em", "50em"],
)


def message_box(chat_message: ChatMessage) -> rx.Component:
    """Each message from the chat history gets its bounding box. Depending on the sender
    the message is aligned to the left for the LLM and aligned to the right for the user
    .
    """
    return rx.box(
        rx.box(
            rx.markdown(
                chat_message.message,
                background_color=rx.cond(
                    chat_message.is_llm, rx.color("mauve", 4), rx.color("blue", 4)
                ),
                color=rx.cond(
                    chat_message.is_llm, rx.color("mauve", 12), rx.color("blue", 12)
                ),
                **message_style,
            ),
            text_align=rx.cond(chat_message.is_llm, "left", "right"),
            margin_top="1em",
        ),
        width="100%",
    )


def chat_form() -> rx.Component:
    """
    Render the chat form for user input. Includes button to send Reply and button to
    check the answer.
    """
    return rx.form(
        rx.vstack(
            rx.text_area(
                name="user_response",
                placeholder="Your Answer",
                required=True,
                width="100%",
            ),
            rx.hstack(
                rx.button("Submit", type="submit"),
                rx.cond(ChatState.did_submit, rx.text("Reply sent!"), rx.fragment()),
                # rx.fragment() is placeholder for now
                rx.button("Check Answer", type="submit"),
            ),
        ),
        on_submit=ChatState.handle_chat_submit,
        reset_on_submit=True,
    )


def chat_default() -> rx.Component:
    """Renders the web page."""
    return rx.container(
        rx.box(
            rx.vstack(
                rx.heading("Exercise number i!", size="5"),
                rx.box(
                    rx.foreach(ChatState.messages, message_box),
                    width="100%",
                    overflow="auto",  # Chat history becomes scrollable
                    max_height="60vh",
                    padding_right="8px",
                ),
                chat_form(),
                spacing="5",
                justify="center",
                min_height="15vh",
            ),
            width="100%",
        ),
        width="100%",
    )
