"""Displays the submitted chat messages"""

from typing import Optional

import reflex as rx

import aitutor.routes as routes
from aitutor.pages.navbar import with_navbar
from aitutor.models import Exercise, ExerciseResult
from aitutor.auth.protection import require_role_at_least
from aitutor.models import UserRole
from aitutor.auth.state import SessionState
from aitutor.pages.chat import CHECK_RESULT_ROLE
from aitutor.pages.chat import message_box


class ChatMessage(rx.Base):
    """
    Class to make handling ChatMessages easier and help differentiate between authors of
    chat messages.
    """

    message: str
    is_llm: bool = False
    is_check_result: bool = False
    # check_passed is used to color the check result message
    check_passed: bool = False


class FinishedViewState(SessionState):
    """Handles the ChatState."""

    messages: list[ChatMessage] = []
    current_exercise: Optional[Exercise] = None
    exercise_title: str = "No Exercise Selected"

    @rx.event
    def load_finished_exercise(self):
        """Loads the finished exercise."""
        with rx.session() as session:
            exercise = session.exec(
                Exercise.select().where(Exercise.id == self.exercise_id)
            ).one_or_none()
            if exercise:
                self.current_exercise = exercise
                self.exercise_title = exercise.title
                self.messages = []
                self.load_finished_conversation()
            else:
                yield rx.redirect(routes.NOT_FOUND)

    def load_finished_conversation(self):
        """Loads the finished conversation."""
        userinfo_id: Optional[int] = self.user_id
        if self.current_exercise and userinfo_id:
            with rx.session() as session:
                exercise_result = session.exec(
                    ExerciseResult.select().where(
                        ExerciseResult.exercise_id == self.current_exercise.id,
                        ExerciseResult.userinfo_id == userinfo_id,
                    )
                ).one_or_none()

                if exercise_result:
                    for msg in exercise_result.finished_conversation:
                        if msg["role"] in ["user", "assistant", CHECK_RESULT_ROLE]:
                            self.append_chat_message(
                                msg["content"],
                                is_llm=(msg["role"] == "assistant"),
                                is_check_result=(msg["role"] == CHECK_RESULT_ROLE),
                                check_passed=msg.get("check_passed", False),
                            )

    def append_chat_message(
        self,
        message,
        is_llm: bool = False,
        is_check_result: bool = False,
        check_passed: bool = False,
    ):
        """
        Once a new message is generated by the user it is appended to the list of
        messages in ChatState.
        """
        self.messages.append(
            ChatMessage(
                message=message,
                is_llm=is_llm,
                is_check_result=is_check_result,
                check_passed=check_passed,
            )
        )


@with_navbar
@require_role_at_least(UserRole.STUDENT)
def finished_view_default() -> rx.Component:
    """Renders the web page."""
    return rx.container(
        rx.box(
            rx.vstack(
                rx.hstack(
                    rx.heading(
                        "Exercise: ",
                        size="5",
                    ),
                    rx.icon(
                        "circle-check",
                        color="green",
                    ),
                    align="center",
                    justify="between",
                    width="100%",
                ),
                rx.auto_scroll(
                    rx.foreach(
                        FinishedViewState.messages,
                        message_box,
                    ),
                    scroll_to_bottom_on_update=True,
                    width="100%",
                    flex="1",
                    padding_right="8px",
                ),
                spacing="5",
                justify="start",
                min_height="85vh",
                max_height="85vh",
                height="100%",
            ),
            width="100%",
        ),
        align_items="center",
        width="100%",
    )
