"""Module defining database models."""

import reflex as rx
from passlib.context import CryptContext
from sqlmodel import Field, Column, JSON, Relationship, DateTime
from typing import Optional, List
from datetime import datetime
from sqlalchemy.sql import func

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


class Tag(rx.Model, table=True):  # type: ignore
    """Tag model for storing allowed tags."""

    id: Optional[int] = Field(default=None, primary_key=True)  # Automatische ID
    name: str = Field(unique=True, nullable=False, index=True)  # Tag-Name, einzigartig

    def __repr__(self):
        return f"<Tag(name='{self.name}')>"


class Exercise(rx.Model, table=True):  # type: ignore
    """Exercise model for storing exercises."""

    id: Optional[int] = Field(default=None, primary_key=True)  # Automatische ID
    title: str = Field(nullable=False)  # Titel der Übung
    prompt: str = Field(nullable=False, default="")  # Prompt für das LLM
    description: Optional[str] = Field(default=None)  # Beschreibung der Übung
    tags: List[str] = Field(
        sa_column=Column(JSON), default=[]
    )  # Liste der Tags als JSON
    image: Optional[str] = Field(default=None)  # Pfad oder URL zum Bild

    # Connects to ExerciseResult.exercise
    submissions: List["ExerciseResult"] = Relationship(back_populates="exercise")

    def __repr__(self):
        return f"<Exercise(title='{self.title}', tags={self.tags})>"


class ExerciseResult(rx.Model, table=True):  # type: ignore
    """
    ExerciseResult model for storing the result of an exercise submitted by a user.

    ExerciseResult is mapped to a SQL Table as it inherits from rx.Model and table=True.
    Every attribute represents a column in the SQL Table.

    Attributes:
    id (int): Primary Key of the ExerciseResult.
    exercise_id (int): Foreign Key associated with Primary Key of the exercise.
    time_stamp (datetime): DateTime of most recent change in Servertime.
    exercise (Optional["Exercise"]): Associated Exercise. Many-To-One Relationship.
    user (Optional["User"]): Associated User. Many-To-One Relationship.
    conversation_text (JSON): Conversation Text of the user and Chatbot stored as JSON.
    """

    # id is generated by SQL.
    id: Optional[int] = Field(default=None, primary_key=True)
    exercise_id: int = Field(foreign_key="exercise.id")
    time_stamp: datetime = Field(
        sa_column=Column(
            type_=DateTime(timezone=True),
            default=func.now(),  # datetime of server
            onupdate=func.now(),  # time_stamp pdated when database entry is modified
            nullable=False,
        )
    )

    # TODO When passing messages to the OpenAI API to create prompts, the message is
    # passed as a list of dictionaries. Each individual message is represented as a
    # dictionary. Dictionaries must be converted to JSON before being stored in the DB.
    # FIXME Consider chaning default value. Depends on further implementation.
    conversation_text: JSON = Field(sa_column=Column(type_=JSON, default=lambda: []))

    # Connects to Exercise.submissions
    exercise: Optional["Exercise"] = Relationship(back_populates="submissions")

    def __repr__(self):
        if self.exercise is None:
            # TODO: Do exercise and user need to be Optional?
            return (
                "<ExerciseResult(ExerciseName=None, UserEmail=None, LastUpdate=None)>"
            )
        else:
            return f"""
            <ExerciseResult(
            ExerciseName='{self.exercise.title}', 
            LastUpdate='{self.time_stamp}'
            )>
        """
