"""The state for the finished view page."""

import reflex as rx
from typing import Optional
from sqlmodel import select
from reflex_local_auth import LocalUser

import aitutor.routes as routes
from aitutor.models import Exercise, ExerciseResult
from aitutor.auth.state import SessionState
from aitutor.pages.chat.state import ChatMessage, Role


class FinishedViewTeacherState(SessionState):
    """The State for the finished view."""

    messages: list[ChatMessage] = []
    current_exercise: Optional[Exercise] = None
    username: str
    exercise_title: str = "No Exercise Selected"

    @rx.var
    def submissions_url(self) -> str:
        """Returns the URL for the chat page."""
        return (
            f"{routes.SUBMISSIONS}/{str(self.router.page.params.get('exercise_id', 0))}"
        )

    @rx.event
    def on_load(self):
        """Loads the finished exercise."""
        with rx.session() as session:
            exercise = session.exec(
                Exercise.select().where(Exercise.id == int(self.exercise_id))
            ).one_or_none()
            if exercise:
                self.current_exercise = exercise
                self.exercise_title = exercise.title
                self.messages = []
                self.load_finished_conversation()
            else:
                yield rx.redirect(routes.NOT_FOUND)
            self.username = (
                session.exec(
                    select(LocalUser.username).where(
                        LocalUser.id == int(self.url_user_id)
                    )
                ).one_or_none()
                or ""
            )

    def load_finished_conversation(self):
        """Loads the finished conversation."""
        url_user_id: Optional[int] = int(self.url_user_id)
        if self.current_exercise and url_user_id:
            with rx.session() as session:
                exercise_result = session.exec(
                    ExerciseResult.select().where(
                        ExerciseResult.exercise_id == self.current_exercise.id,
                        ExerciseResult.userinfo_id == url_user_id,
                    )
                ).one_or_none()

                if exercise_result:
                    for msg in exercise_result.finished_conversation:
                        if msg["role"] != Role.SYSTEM.value:
                            self.append_chat_message(
                                msg["content"],
                                role=Role(msg["role"]),
                                check_passed=msg.get("check_passed", False),
                            )

    def append_chat_message(self, message, role: Role, check_passed: bool):
        """
        Once a new message is generated by the user it is appended to the list of
        messages in ChatState.
        """
        self.messages.append(
            ChatMessage(
                message=message,
                role=role,
                check_passed=check_passed,
            )
        )
